<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Shipping</name>
   <tag></tag>
   <elementGuidId>92a908db-85ce-4abb-8fe4-d2776487e265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Shipping' or . = 'Shipping')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.opc-progress-bar-item._active > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Shipping&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f8c3e52-71f8-40ad-81b6-ff28e79ab19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>i18n: item.title, click: $parent.navigateTo</value>
      <webElementGuid>4873f333-8c65-4f0d-bf55-be4718051c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipping</value>
      <webElementGuid>1544cd65-9529-46c5-b51a-33b3de40092b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout&quot;)/ul[@class=&quot;opc-progress-bar&quot;]/li[@class=&quot;opc-progress-bar-item _active&quot;]/span[1]</value>
      <webElementGuid>8e525633-b4e5-4c9c-8b3e-88e032890bc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout']/ul/li/span</value>
      <webElementGuid>13683bd8-ec74-44c6-b05f-20692292f5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Your Password?'])[1]/following::span[1]</value>
      <webElementGuid>170f6aa6-1690-47d1-9350-4cffd57debc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[3]/following::span[2]</value>
      <webElementGuid>44c67345-a8a8-40ad-b12f-37bbb9911b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review &amp; Payments'])[1]/preceding::span[1]</value>
      <webElementGuid>eea9a9c8-7f4f-4e96-8731-253cbd824048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated Total'])[1]/preceding::span[2]</value>
      <webElementGuid>ca9ee79a-1563-44c4-be31-372cc5852861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipping']/parent::*</value>
      <webElementGuid>2d995875-3f4a-420a-acd7-97ffceeef70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>a061fc93-52c6-4bed-a1ac-bf6c3e5316b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Shipping' or . = 'Shipping')]</value>
      <webElementGuid>e9b0f20e-a379-462e-a656-994bc84bf41a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
